Repository DigitalLibraryofTennessee/DLTN_XSLT, pull requests merged in 2019-06, with the labels that each got.

#176 Address DLTN_XSLT-175.
  XSLT/countryqdctomods.xsl
Labels: metadata problem

#177 Address DLTN_XSLT-174.
  XSLT/tslaqdctomods.xsl
Labels: metadata problem

#179 Address DLTN_XSLT-178.
  XSLT/utkmodstomods.xsl
Labels: metadata problem

#183 Add sets for June 2019 testing.
  tests/test_data/tsla_qdc.txt
  tests/test_data/utk_mods.txt
Labels: new sets, unit test

#184 Add three new UTK sets to test data.
  tests/test_data/utk_mods.txt
Labels: new sets, unit test

#186 Address DLTN_XSLT-185.
  tests/test_data/utc_qdc.txt
  tests/validate_scenarios.sh
Labels: unit test

#189 Address DLTN_XSLT-185.
  XSLT/catalogs/cmhf_catalog.xml
  XSLT/catalogs/tsla_catalog.xml
  XSLT/countryqdctomods.xsl
Labels: iiif

#191 Address DLTN_XSLT-190.
  XSLT/utkmodstomods.xsl
Labels: metadata problem
